spring:
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bd_carrito
    username: postgres
    password: admin

openapi:
  project-title: @project.name@
  project-version: @project.version@
  project-description: @project.description@